# Welcome to Jekyll!

# Site settings
title: Vim-CtrlSpace
email: wojtek.ryrych@gmail.com
description: >
  Vim CtrlSpace is *your* Vim Space Controller!
baseurl: ""
url: "https://vim-ctrlspace.github.io/"
twitter_username: "VimCtrlSpace"
github_username:  "vim-ctrlspace/vim-ctrlspace"
excerpt_separator: "<!-- more -->"

# Build settings
markdown: redcarpet
highlighter: rouge
